default:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: '{{ env_var("DBT_DUCKDB", "./lake/dev.duckdb") }}'
    prod:
      type: bigquery
      method: service-account
      project: '{{ env_var("BQ_PROJECT") }}'
      dataset: '{{ env_var("BQ_DATASET") }}'
      keyfile: '{{ env_var("GOOGLE_APPLICATION_CREDENTIALS") }}'
