version: 2
models:
  - name: climate_gold_monthly
    columns:
      - name: location_id
        tests: [not_null]
      - name: y
        tests: [not_null]
      - name: m
        tests: [not_null]
      - name: tavg_c
        tests:
          - accepted_range:
              min_value: -100
              max_value: 100
  - name: climate_gold_normals_1991_2020
    columns:
      - name: location_id
        tests: [not_null]
  - name: climate_gold_anomalies
    columns:
      - name: location_id
        tests: [not_null]
