name: CI

on:
  pull_request:
    branches: ["*"]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: |
          poetry install --no-root
      - name: Ruff
        run: poetry run ruff check .
      - name: Black
        run: poetry run black --check .
      - name: Pytest
        run: poetry run pytest -q
