name: CI
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          pip install poetry dbt-duckdb
          poetry install --no-root
      - name: Pytests
        run: poetry run pytest -q
      - name: dbt compile
        run: dbt --project-dir dbt --profiles-dir dbt compile
